### ISSUE TITLE
Reek configuration?

### ISSUE THREAD

**Issue by jdickey** [whitesmith/rubycritic#21]
When I put a `reek.config` file in my `app/services` directory and run Reek from the command line, it reads and uses the config as expected.  When I run `rubycritic` (1.1.1, as packaged), smells (apparently from Reek) are reported for methods like `#method_missing?`. 

If I make that an _invalid_ Reek config file, then the "Invalid configuration file" message is output twice for each file inspected.

My `app/services/config.reek` is

``` yml

---
ControlParameter:
  exclude:
    - !ruby/regexp /respond_to\?/
```
