### ISSUE TITLE
Ignores .rubycritic.yml file

### ISSUE THREAD

**Issue by cvoltz** [whitesmith/rubycritic#303]
I tried testing with the example `.rubycritic.yml` configuration file:
```
mode_ci:
  enabled: true # default is false
  branch: 'production' # default is master
branch: 'production' # default is master
path: '/tmp/mycustompath' # Set path where report will be saved (tmp/rubycritic by default)
threshhold_score: 10 # default is 0
deduplicate_symlinks: true # default is false
suppress_ratings: true # default is false
no_browser: true # default is false
format: console # Available values are: html, json, console, lint. Default value is html.
minimum_score: 95 # default is 0
paths: # Files to analyse.
  - 'app/controllers/'
  - 'app/models/'
```
Changes in the configuration file (e.g., `no_browser`, `path`, and `paths`), don't affect the settings rubycritic actually uses when it runs. It appears to always use the default settings (i.e., as if the `.rubycritic.yml` wasn't present) unless command line arguments are specified (then the CLI setting is used). When rubycritic runs, it does read the configuration file. It just appears to ignore the settings.

Also, it looks like the documented `format` option for the config file has changed to `formats` but the documentation hasn't been updated to match (see `RubyCritic::Cli::Options::File::formats`).
