### ISSUE TITLE
Coverage page ignores .resultset.json

### ISSUE THREAD

**Issue by eprislac** [whitesmith/rubycritic#402]
I run specs on Travis CI for pull-requests, but I use Jenkins to generate docs on deployment. I host these directly from Jenkins. So far, I'm able to generate all Rubycritic pages except coverage. Coverage recognizes all my files, but fails to utilize the .resultset.json file I have committed to the repo. All files show up with 0% coverage, even though SimpleCov reports 77% coverage when I look at the results after running my specs.

**Comment by radomirz** [comment]
any news on this issue? @eprislac were you able to get coverage results in the rubycritic report?

**Comment by exoego** [comment]
I have a similar issue on CircleCI.
In CircleCI, files like `.resultset.json` and `rubycricit/overview.html` are typically stored in Artifacts page.

```yaml
      - run:
          name: RubyCritic
          command:  bundle exec rubycritic --no-browser --path artifacts/rubycritic
      - store_artifacts:
          path: artifacts
```
and 
```ruby
  SimpleCov.start 'rails' do
    add_filter 'vendor'
  end
  SimpleCov.coverage_dir('artifacts/coverage')
```
in `spec_helper.rb`.

Then, CircleCI stores .resultset.json and `rubycritic~` files like this:
![image](https://user-images.githubusercontent.com/127635/205644753-50fd6397-449d-438d-a5f0-fb072d365767.png)

However, coverage page ignores the coverage json.

It looks like RubyCritic assumes the default coverage directory is used.
https://github.com/whitesmith/rubycritic/blob/3bc857d2ca399341f4cfff19519cb32cbf29ad78/lib/rubycritic/analysers/coverage.rb#L51

I think it should support different coverage dir, something like this:
```ruby
SimpleCov.coverage_dir(ENV['RUBYCRITIC_COVERAGE_PATH`]) if ENV['RUBYCRITIC_COVERAGE_PATH`]
```

**Comment by exoego** [comment]
The below worked for me. Both coverage and rubycritic results are stored in CircleCI and RubyCritic coverage page shows coverage successfully.

```yaml
      - run:    
          name: RSpec
          command: COVERAGE=1 bundle exec rspec
      - store_artifacts:
          path: coverage
      - run:
          name: RubyCritic
          command:  bundle exec rubycritic --no-browser --path rubycritic
      - store_artifacts:
          path: rubycritic
```
and 
```ruby
  SimpleCov.start 'rails' do
    add_filter 'vendor'
  end
  # SimpleCov.coverage_dir('artifacts/coverage')
```
