### ISSUE TITLE
How to ignore a specific file or file pattern ?

### ISSUE THREAD

**Issue by miguno** [whitesmith/rubycritic#497]
I found an older discussion https://github.com/whitesmith/rubycritic/issues/11 from 2014, but rubycritic has progressed since—such as supporting a `.rubycritic.yml` config file.

My question: How can I ignore a specific file or particular file pattern?

Imagine this `.rubycritic.yml` file:

```yaml
minimum_score: 95 # default: 0
paths:
  - "app/"
  - "db/"      # <=== entire db/ folder is included
  - "config/"
  - "lib/"
  - "script/"
```

Here, how can I exclude a specific file such as `db/queue_schema.rb`?

Think:
```yaml
# Not supported, just to get the idea across.
exclude_paths:
  - "db/queue_schema.rb"
```
