### ISSUE TITLE
Reek custom configuration

### ISSUE THREAD

**Issue by Xadozuk** [whitesmith/rubycritic#56]
I've created a `config.reek` file in the root of my Rails project but it doesn't seem to be read by reek when run through `rubycritic` command. 
I've tested with only the `reek` command and it works well, my configuration is applied.

Is this the normal behavior or am I doing something wrong ?
I saw the issue #21 and it seems this was possible in version 1.1.1 of rubycritic.

My `config.reek`
```yaml
UncommunicativeVariableName:
  accept:
    - '_'
    - 'a'
    - 'e'
```
|            | Version |
|------------|---------|
| Ruby       | 2.1.6   |
| RubyCritic | 1.4.0   |
