### ISSUE TITLE
Support project specific Reek configuration

### ISSUE THREAD

**Issue by lucasmazza** [whitesmith/rubycritic#73]
RubyCritic ships with a built in `config.reek` file but I believe it would be interesting to support a local `.reek` file (or an argument on the CLI) and an option on the Ruby API to pass the pathname. What do you folks think about it?

**Comment by troessner** [comment]
>> RubyCritic ships with a built in config.reek file but I believe it would be interesting to support a local .reek file (or an argument on the CLI) and an option on the Ruby API to pass the pathname. What do you folks think about it?

**Big** :+1:  from my side. Especially since we have made Reek's configuration abilities [significantly more powerful](https://github.com/troessner/reek#configuration-options) .

**Comment by lucasmazza** [comment]
:+1: I'll see if I can sketch something for that then.

**Comment by troessner** [comment]
That would be awesome!

**Comment by guilhermesimoes** [comment]
When Reek runs it automatically picks up any `.reek` files along the way. It should behave exactly the same way with RubyCritic. I don't think any extra configuration should be needed. In fact, it used to work like that but I guess it stopped working :(

**Comment by guilhermesimoes** [comment]
Also, here's an explanation for a few choices in the opinionated [`config.reek`][1] that ships with RubyCritic:

* NestedIterators: max_allowed_nesting: 2

  This is so we don't flag Rails' `respond_to do |format|`.

* `Uncommunicative*Name`

  These smells conflate two separate issues: quality and style.
  Short names like `i` or `n` = quality issue
  Names using snake_case or numbers (what's wrong with numbers btw?) = style issue

  And I'd rather leave style issues for Rubocop.

These choices should still be allowed to be overridden if you have a local `.reek` file though. But I guess that's not happening right now.

[1]: https://github.com/whitesmith/rubycritic/blob/5f3de42dda75a57f84844dd099b3310338a16f01/lib/rubycritic/analysers/helpers/config.reek

**Comment by lucasmazza** [comment]
@guilhermesimoes I believe reek isn't picking up the local configuration because rubycritic is explicitly [passing it's own](https://github.com/whitesmith/rubycritic/blob/5f3de42dda75a57f84844dd099b3310338a16f01/lib/rubycritic/analysers/helpers/reek.rb#L8-L12)? So the default always take precedence over the local one.

**Comment by troessner** [comment]
>> @guilhermesimoes I believe reek isn't picking up the local configuration because rubycritic is explicitly passing it's own? So the default always take precedence over the local one.

Yep, that's exactly why.
Let's fix that.:)

**Comment by troessner** [comment]
@lucasmazza @Onumis let's drop the default config file for Reek in RubyCritic.
Reek has an excellent [configuration loading mechanism](https://github.com/troessner/reek#configuration-loading) and we should just leverage that.
Additionally we [revamped our docs](https://github.com/troessner/reek#configuration-options) significantly so it should be so easy for people to configure Reek, that I don't think we need any of the RubyCritic defaults now.  

I think we should stick with Reek defaults. After all, every user can easily change them via our standard configuration loading.

What do you guys think?

**Comment by Onumis** [comment]
It makes sense but I'm concerned about current users suddenly seeing different things when they update RubyCritic.
Do you happen to know if the differences between our default config file for Reek and Reek's defaults?

For example, if `DuplicateMethodCall: max_calls: 2` is different, people will probably get very confused.

**Comment by guilhermesimoes** [comment]
I agree with what you're saying @Onumis. But maybe you should take the opportunity of having moved on to 2.0.0 and change this ASAP. Break what you can while you still can.

Removing this default config file is probably easier than refactoring a ton of code just to accommodate it.

I tried to make RubyCritic a little opinionated because I was mimicking Code Climate. Clearly people want more control over everything: what smells to check for, how ratings should be shown (with letters, with numbers or with colours) and so on. I say give the people what they want – that's the beauty of OSS when compared to a closed source service :)

**Comment by troessner** [comment]
>> Do you happen to know if the differences between our default config file for Reek and Reek's defaults?

Let me list Reek defaults after the "#":

```
Attribute:
  enabled: false
  # Enabled
DuplicateMethodCall:
  max_calls: 2
  # 1
IrresponsibleModule:
  enabled: false
  # 1
NestedIterators:
  max_allowed_nesting: 2
  # 1
TooManyStatements:
  enabled: false
  # Enabled
UncommunicativeMethodName:
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  # Reek also has
  - !ruby/regexp /[A-Z]/
UncommunicativeParameterName:
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /^_/
  # Reek also has
  - !ruby/regexp /[A-Z]/
UncommunicativeVariableName:
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  #  That's exactly how it is in Reek right now
UtilityFunction:
  enabled: false
  # enabled by default. See below.
```

I can see why people would disable this but ever since we made it possible to ignore it for private methods (which is the nr. 1 annoyance) via https://github.com/troessner/reek/pull/698  I don't think this should be disabled anymore since  UtilityFunction on public methods are normally valid.

I believe we should take the Reek defaults in all of the cases above and thus get rid of the special configuration in RubyCritic. 

What do you guys think?
